<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>EasyPoint.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyPoint.Application\EasyPoint.Application.csproj" />
    <ProjectReference Include="..\EasyPoint.Infrastructure\EasyPoint.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>
</Project>
