<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>EasyPoint.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyPoint.Domain\EasyPoint.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Stores\Update\" />
  </ItemGroup>
</Project>
